grep "\"Method\":\"NtCreateFile\"" %1 > NtCreateFile.txt
grep "\"Method\":\"NtOpenDirectoryObject\"" %1 > NtOpenDirectoryObject.txt
grep "\"Method\":\"NtOpenFile\"" %1 > NtOpenFile.txt
grep "\"Method\":\"NtQueryAttributesFile\"" %1 > NtQueryAttributesFile.txt
grep "\"Method\":\"NtReadFile\"" %1 > NtReadFile.txt
grep "\"Method\":\"NtSetInformationFile\"" %1 > NtSetInformationFile.txt
grep "\"Method\":\"NtWriteFile\"" %1 > NtWriteFile.txt
grep "\"Method\":\"NtCreateUserProcess\"" %1 > NtCreateUserProcess.txt
grep "\"Method\":\"NtOpenProcess\"" %1 > NtOpenProcess.txt
grep "\"Method\":\"NtProtectVirtualMemory\"" %1 > NtProtectVirtualMemory.txt
grep "\"Method\":\"NtTerminateProcess\"" %1 > NtTerminateProcess.txt
grep "\"Method\":\"NtQueryValueKey\"" %1 > NtQueryValueKey.txt
grep "\"Method\":\"NtQueryKey\"" %1 > NtQueryKey.txt
grep "\"Method\":\"NtSetValueKey\"" %1 > NtSetValueKey.txt
grep "\"Method\":\"NtAllocateVirtualMemory\"" %1 > NtAllocateVirtualMemory.txt
grep "\"Method\":\"NtQueryInformationProcess\"" %1 > NtQueryInformationProcess.txt
grep "\"Method\":\"NtMapViewOfSection\"" %1 > NtMapViewOfSection.txt
grep "\"Method\":\"NtUnmapViewOfSection\"" %1 > NtUnmapViewOfSection.txt
grep "\"Method\":\"NtFreeVirtualMemory\"" %1 > NtFreeVirtualMemory.txt
grep "\"Method\":\"NtReadVirtualMemory\"" %1 > NtReadVirtualMemory.txt
grep "\"Method\":\"NtAdjustPrivilegesToken\"" %1 > NtAdjustPrivilegesToken.txt
grep "\"Method\":\"NtClose\"" %1 > NtClose.txt
grep "\"Method\":\"GetComputerNameExW\"" %1 > GetComputerNameExW.txt
grep "\"Method\":\"NtUserMessageCall\"" %1 > NtUserMessageCall.txt
grep "\"Method\":\"NtUserCallTwoParam\"" %1 > NtUserCallTwoParam.txt
grep "\"Method\":\"NtQueryInformationFile\"" %1 > NtQueryInformationFile.txt
grep "\"Method\":\"NtOpenThread\"" %1 > NtOpenThread.txt
grep "\"Method\":\"NtOpenKeyEx\"" %1 > NtOpenKeyEx.txt